services:
  - type: web
    name: api_webtracnghiem
    runtime: docker
    repo: https://github.com/Kljustin/apirender.git
    branch: main
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:NzglC196YAaMuvIjyDoSeiP8TWNoNCGwUd5L2n7owKk=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql12772114
      - key: DB_USERNAME
        value: sql12772114
      - key: DB_PASSWORD
        value: ssIEAPLF4Q